use_frameworks!

platform :ios, '13.0'

install! 'cocoapods', :disable_input_output_paths => false

target 'herdr' do
   project 'herdr/herdr.xcodeproj'
   
   pod 'MultiPlatformLibrary', :path => '../app'
   pod 'MultiPlatformLibraryMvvm', :git => 'https://github.com/icerockdev/moko-mvvm.git', :tag => 'release/0.7.1'
   pod 'SecureDefaults', '1.0.5'
   pod 'AppAuth'
end
