use_frameworks!

platform :ios, '9.0'

install! 'cocoapods', :deterministic_uuids => false

target 'herdr' do
   project 'herdr/herdr.xcodeproj'
   pod 'app', :path => '/Users/f8full/Documents/GitHub/herdr/app'
end