source 'https://cdn.cocoapods.org/'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!
platform :ios, '11.0'

# workaround for https://github.com/CocoaPods/CocoaPods/issues/8073
# need for correct invalidate of cache MultiPlatformLibrary.framework
install! 'cocoapods', :disable_input_output_paths => true

pre_install do |installer|
  # We represent a Kotlin/Native module to CocoaPods as a vendored framework.
  # CocoaPods needs access to such frameworks during installation process to obtain
  # their type (static or dynamic) and configure the Xcode project accordingly.
  # Build MultiPlatformLibrary framework to correct install Pod
  puts "prepare MultiPlatformLibrary.framework (require some time...)"
  `cd .. && ./gradlew :app:syncMultiPlatformLibraryDebugFrameworkIosX64`
  puts "preparing MultiPlatformLibrary.framework complete"
end

target 'iosApp' do
  pod 'AppAuth', '1.4.0'
  pod 'SecureDefaults', '1.0.0'
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/Buttons+Theming'
  pod 'MaterialComponents/Cards'
  pod 'MaterialComponents/Cards+Theming'
  pod 'MaterialComponents/schemes/Shape'
  # pod 'MaterialComponents/TextControls+OutlinedTextFields'
  pod 'MaterialComponents/TextFields'
  pod 'MultiPlatformLibrary', :path => '../app'
  pod 'MultiPlatformLibraryMvvm/Core',
    :git => 'https://github.com/icerockdev/moko-mvvm.git', :tag => 'release/0.9.1'
end